services:
  web:
    build: .
    container_name: django-web
    restart: always
    volumes:
      - .:/app
      - ./media:/app/media
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always
    ports:
      - "8554:8554"
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - .:/app
    command: /app/mediamtx.yml

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web