version: '3.8'

services:
  web:
    build: .
    container_name: django-web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    command: python manage.py runserver 0.0.0.0:8000