# Generated by Django 5.2.5 on 2025-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='camera',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
