# Generated by Django 5.2.5 on 2025-08-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_delete_admin_camera_senha_camera_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='senha',
        ),
    ]
