# Generated by Django 5.2.5 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0004_remove_camera_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="rtsp_sub",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
